import { DateRangeProvider } from "@/context/DateRangeContext";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <DateRangeProvider>{children}</DateRangeProvider>
      </body>
    </html>
  );
}
